import AppKit
import UniformTypeIdentifiers

/// One thing you copied.
struct ClipboardItem: Identifiable, Equatable {
    enum Content: Equatable {
        case text(String)
        case link(URL)
        case image(NSImage, file: URL)
        case files([URL])
        case color(NSColor)
    }

    enum Kind: String, CaseIterable, Identifiable {
        case all = "All"
        case text = "Text"
        case links = "Links"
        case images = "Images"
        case files = "Files"
        var id: String { rawValue }
    }

    let id = UUID()
    var content: Content
    var copied: Date
    var sourceName: String?
    var sourceBundleID: String?
    var isPinned = false

    var kind: Kind {
        switch content {
        case .text, .color: return .text
        case .link: return .links
        case .image: return .images
        case .files: return .files
        }
    }

    /// What the row shows as its main line, and what search looks through.
    var title: String {
        switch content {
        case let .text(text):
            return text.trimmingCharacters(in: .whitespacesAndNewlines)
                .components(separatedBy: .newlines).first(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty }) ?? text
        case let .link(url): return url.host.map { "\($0)\(url.path == "/" ? "" : url.path)" } ?? url.absoluteString
        case .image: return "Image"
        case let .files(urls): return urls.count == 1 ? urls[0].lastPathComponent : "\(urls.count) files"
        case let .color(color): return color.hexString
        }
    }

    var detail: String {
        switch content {
        case let .text(text):
            let lines = text.components(separatedBy: .newlines).count
            return lines > 1 ? "\(text.count) characters · \(lines) lines" : "\(text.count) characters"
        case let .link(url): return url.absoluteString
        case let .image(image, _):
            let pixels = image.representations.first.map { "\($0.pixelsWide)×\($0.pixelsHigh)" }
            return pixels ?? "Image"
        case let .files(urls): return urls.map(\.lastPathComponent).joined(separator: ", ")
        case .color: return "Colour"
        }
    }

    var searchText: String {
        switch content {
        case let .text(text): return text
        case let .link(url): return url.absoluteString
        case let .files(urls): return urls.map(\.path).joined(separator: " ")
        case let .color(color): return color.hexString
        case .image: return "image"
        }
    }

    static func == (lhs: ClipboardItem, rhs: ClipboardItem) -> Bool {
        lhs.id == rhs.id && lhs.isPinned == rhs.isPinned && lhs.copied == rhs.copied
    }
}

/// Everything you copy, screenshots you take and files you drop on the notch, most
/// recent first — the history macOS's own clipboard forgets. Kept in memory only,
/// so it's gone when Island quits.
@MainActor
final class ClipboardHistory: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    /// Reported for each new copy, so the island can acknowledge it.
    var onCopy: ((ClipboardItem) -> Void)?
    /// Reported for each new screenshot, so the island can show it as it arrives.
    var onScreenshot: ((ClipboardItem) -> Void)?

    private static let limit = 60
    private let storage = FileManager.default.temporaryDirectory.appendingPathComponent("IslandClipboard", isDirectory: true)
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    /// Set while Island itself writes to the pasteboard, so it isn't recorded again.
    private var ignoreChangeCount: Int?
    private var folderSource: DispatchSourceFileSystemObject?
    private var watchedFolder: URL?
    private var knownScreenshots: Set<String> = []
    private var locationTimer: Timer?

    /// Password managers mark what they copy this way and ask that it not be kept.
    private static let privateTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    init() {
        try? FileManager.default.removeItem(at: storage)
        try? FileManager.default.createDirectory(at: storage, withIntermediateDirectories: true)
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer

        watchScreenshotFolder()
        // The screenshot location can be changed from the Screenshot app's Options menu.
        locationTimer = Timer.scheduledTimer(withTimeInterval: 15, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.watchScreenshotFolder() }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        locationTimer?.invalidate()
        locationTimer = nil
        folderSource?.cancel()
        folderSource = nil
        watchedFolder = nil
    }

    // MARK: Adding things that weren't copied

    /// Files and images dropped on the island.
    /// `added` is told about each item as it lands, so the island can offer what to do with it.
    func accept(providers: [NSItemProvider], added: ((ClipboardItem) -> Void)? = nil) -> Bool {
        var accepted = false
        for provider in providers {
            if provider.hasItemConformingToTypeIdentifier(UTType.fileURL.identifier) {
                accepted = true
                _ = provider.loadObject(ofClass: URL.self) { url, _ in
                    guard let url else { return }
                    DispatchQueue.main.async {
                        MainActor.assumeIsolated {
                            if let item = self.add(fileURL: url) { added?(item) }
                        }
                    }
                }
            } else if provider.hasItemConformingToTypeIdentifier(UTType.image.identifier) {
                accepted = true
                provider.loadDataRepresentation(forTypeIdentifier: UTType.image.identifier) { data, _ in
                    guard let data, let image = NSImage(data: data) else { return }
                    DispatchQueue.main.async {
                        MainActor.assumeIsolated {
                            if let item = self.add(image: image) { added?(item) }
                        }
                    }
                }
            }
        }
        return accepted
    }

    /// An image Island already has in memory (album artwork, for one).
    @discardableResult
    func add(image: NSImage, source: String? = nil) -> ClipboardItem? {
        guard let file = save(image) else { return nil }
        return insert(.image(image, file: file), sourceName: source, sourceBundleID: nil)
    }

    /// A file on disk: kept as an image if it is one, so it gets a real thumbnail.
    @discardableResult
    func add(fileURL url: URL, source: String? = nil) -> ClipboardItem? {
        let isImage = (UTType(filenameExtension: url.pathExtension)?.conforms(to: .image)) ?? false
        if isImage, let image = NSImage(contentsOf: url) {
            return insert(.image(image, file: url), sourceName: source, sourceBundleID: nil)
        }
        return insert(.files([url]), sourceName: source, sourceBundleID: nil)
    }

    private func insert(_ content: ClipboardItem.Content, sourceName: String?, sourceBundleID: String?) -> ClipboardItem {
        var item = ClipboardItem(content: content, copied: Date(), sourceName: sourceName, sourceBundleID: sourceBundleID)
        if let existing = items.firstIndex(where: { Self.sameContent($0.content, content) }) {
            item.isPinned = items[existing].isPinned
            items.remove(at: existing)
        }
        items.insert(item, at: insertionIndex(pinned: item.isPinned))
        trim()
        return item
    }

    private func trim() {
        while items.count > Self.limit, let last = items.lastIndex(where: { !$0.isPinned }) {
            remove(items[last])
        }
    }

    // MARK: Screenshots

    private static var screenshotFolder: URL {
        let configured = UserDefaults(suiteName: "com.apple.screencapture")?.string(forKey: "location")
        if let configured, !configured.isEmpty {
            let expanded = (configured as NSString).expandingTildeInPath
            var isDirectory: ObjCBool = false
            if FileManager.default.fileExists(atPath: expanded, isDirectory: &isDirectory), isDirectory.boolValue {
                return URL(fileURLWithPath: expanded, isDirectory: true)
            }
        }
        return FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Desktop", isDirectory: true)
    }

    private func watchScreenshotFolder() {
        guard timer != nil else { return }
        let folder = Self.screenshotFolder
        guard folder != watchedFolder else { return }

        folderSource?.cancel()
        folderSource = nil
        watchedFolder = folder
        knownScreenshots = Set(screenshotNames(in: folder))

        let descriptor = open(folder.path, O_EVTONLY)
        guard descriptor >= 0 else { return }
        let source = DispatchSource.makeFileSystemObjectSource(fileDescriptor: descriptor, eventMask: .write, queue: .main)
        source.setEventHandler { [weak self] in
            MainActor.assumeIsolated { self?.scanForScreenshots() }
        }
        source.setCancelHandler { close(descriptor) }
        source.resume()
        folderSource = source
    }

    /// Screenshot files carry a Spotlight attribute from the moment they are written,
    /// which identifies them in any language, whatever the file is called.
    private func screenshotNames(in folder: URL) -> [String] {
        guard let names = try? FileManager.default.contentsOfDirectory(atPath: folder.path) else { return [] }
        return names.filter { name in
            guard !name.hasPrefix(".") else { return false }
            let path = folder.appendingPathComponent(name).path
            return getxattr(path, "com.apple.metadata:kMDItemIsScreenCapture", nil, 0, 0, 0) > 0
        }
    }

    private func scanForScreenshots() {
        guard let folder = watchedFolder else { return }
        for name in screenshotNames(in: folder) where !knownScreenshots.contains(name) {
            knownScreenshots.insert(name)
            let url = folder.appendingPathComponent(name)
            if let item = add(fileURL: url, source: "Screenshot") {
                if copiesScreenshots { putScreenshotOnPasteboard(url) }
                onScreenshot?(item)
            }
        }
    }

    /// Halo just wrote to the pasteboard itself (Smart Drop results): don't record it again.
    func ignoreCurrentPasteboard() {
        ignoreChangeCount = NSPasteboard.general.changeCount
        lastChangeCount = NSPasteboard.general.changeCount
    }

    /// Like a snipping tool: each new screenshot is ready to paste with ⌘V.
    var copiesScreenshots = true

    /// The picture as PNG and TIFF, plus the file itself, in one pasteboard item, so image
    /// apps paste the picture and Finder or chat apps can take the file.
    private func putScreenshotOnPasteboard(_ url: URL, attempt: Int = 0) {
        guard let data = try? Data(contentsOf: url), let image = NSImage(data: data), image.isValid else {
            // The file can still be being written when it first appears.
            if attempt < 6 {
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.25) { [weak self] in
                    self?.putScreenshotOnPasteboard(url, attempt: attempt + 1)
                }
            }
            return
        }
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        if url.pathExtension.lowercased() == "png" {
            item.setData(data, forType: .png)
        } else if let tiff = image.tiffRepresentation, let rep = NSBitmapImageRep(data: tiff),
                  let png = rep.representation(using: .png, properties: [:]) {
            item.setData(png, forType: .png)
        }
        if let tiff = image.tiffRepresentation { item.setData(tiff, forType: .tiff) }
        item.setString(url.absoluteString, forType: .fileURL)
        pasteboard.writeObjects([item])
        // Island put it there; it is already in the history as the screenshot.
        ignoreChangeCount = pasteboard.changeCount
        lastChangeCount = pasteboard.changeCount
    }

    // MARK: Using items

    /// Puts an item back on the clipboard, and moves it to the top.
    func copy(_ item: ClipboardItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch item.content {
        case let .text(text):
            pasteboard.setString(text, forType: .string)
        case let .link(url):
            pasteboard.writeObjects([url as NSURL])
            pasteboard.setString(url.absoluteString, forType: .string)
        case let .image(image, _):
            pasteboard.writeObjects([image])
        case let .files(urls):
            pasteboard.writeObjects(urls as [NSURL])
        case let .color(color):
            pasteboard.writeObjects([color])
        }
        ignoreChangeCount = pasteboard.changeCount
        lastChangeCount = pasteboard.changeCount

        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        var moved = items.remove(at: index)
        moved.copied = Date()
        items.insert(moved, at: insertionIndex(pinned: moved.isPinned))
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        // Only delete image files Island wrote itself, never your screenshots or files.
        if case let .image(_, file) = item.content, file.path.hasPrefix(storage.path) {
            try? FileManager.default.removeItem(at: file)
        }
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        var changed = items.remove(at: index)
        changed.isPinned.toggle()
        items.insert(changed, at: insertionIndex(pinned: changed.isPinned))
    }

    /// Clears everything except pinned items.
    func clearUnpinned() {
        for item in items where !item.isPinned { remove(item) }
    }

    private func insertionIndex(pinned: Bool) -> Int {
        pinned ? 0 : items.firstIndex(where: { !$0.isPinned }) ?? items.count
    }

    // MARK: Watching the pasteboard

    private func check() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        if ignoreChangeCount == pasteboard.changeCount { return }

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.privateTypes) else { return }
        guard let content = read(pasteboard, types: types) else { return }

        let source = NSWorkspace.shared.frontmostApplication
        var item = ClipboardItem(content: content, copied: Date(),
                                 sourceName: source?.localizedName, sourceBundleID: source?.bundleIdentifier)

        // Copying the same thing again moves it up rather than adding a duplicate.
        if let existing = items.firstIndex(where: { Self.sameContent($0.content, content) }) {
            item.isPinned = items[existing].isPinned
            let old = items.remove(at: existing)
            if case let .image(_, file) = old.content, case let .image(_, newFile) = content, file != newFile,
               file.path.hasPrefix(storage.path) {
                try? FileManager.default.removeItem(at: file)
            }
        }
        items.insert(item, at: insertionIndex(pinned: item.isPinned))

        while items.count > Self.limit, let last = items.lastIndex(where: { !$0.isPinned }) {
            remove(items[last])
        }
        onCopy?(item)
    }

    private func read(_ pasteboard: NSPasteboard, types: Set<NSPasteboard.PasteboardType>) -> ClipboardItem.Content? {
        if types.contains(.fileURL),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls)
        }
        if types.contains(.png) || types.contains(.tiff), !types.contains(.string),
           let image = NSImage(pasteboard: pasteboard), let file = save(image) {
            return .image(image, file: file)
        }
        if types.contains(.color), !types.contains(.string),
           let color = NSColor(from: pasteboard) {
            return .color(color)
        }
        if let text = pasteboard.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.contains(where: \.isWhitespace), let url = URL(string: trimmed),
               let scheme = url.scheme?.lowercased(), ["http", "https"].contains(scheme), url.host != nil {
                return .link(url)
            }
            return .text(text)
        }
        // An image copied from a browser comes with an HTML description as well.
        if types.contains(.png) || types.contains(.tiff), let image = NSImage(pasteboard: pasteboard), let file = save(image) {
            return .image(image, file: file)
        }
        return nil
    }

    private func save(_ image: NSImage) -> URL? {
        guard let tiff = image.tiffRepresentation, let bitmap = NSBitmapImageRep(data: tiff),
              let png = bitmap.representation(using: .png, properties: [:]) else { return nil }
        let url = storage.appendingPathComponent("Copied \(UUID().uuidString.prefix(8)).png")
        return (try? png.write(to: url)) != nil ? url : nil
    }

    private static func sameContent(_ lhs: ClipboardItem.Content, _ rhs: ClipboardItem.Content) -> Bool {
        switch (lhs, rhs) {
        case let (.text(a), .text(b)): return a == b
        case let (.link(a), .link(b)): return a == b
        case let (.files(a), .files(b)): return a == b
        case let (.color(a), .color(b)): return a.hexString == b.hexString
        case let (.image(a, _), .image(b, _)): return a.tiffRepresentation == b.tiffRepresentation
        default: return false
        }
    }
}

extension NSColor {
    var hexString: String {
        guard let rgb = usingColorSpace(.sRGB) else { return "Colour" }
        return String(format: "#%02X%02X%02X", Int(rgb.redComponent * 255), Int(rgb.greenComponent * 255),
                      Int(rgb.blueComponent * 255))
    }
}
